services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      target: dev
    volumes:
      # ホスト側のファイルシステムのパスを直接、指定しているため、
      # これはバインドマウント。
      - ./api:/api
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/app?schema=public"
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    restart: always
    # dbを先に起動
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "app"
    ports:
      - 5433:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
      # ファイルを変更した際に再ビルドするのは手間なため、
      # Dockerfileではなくvolumesでマウント
      - ./docker/db/init-scrips:/docker-entrypoint-initdb.d
    stdin_open: true
    tty: true
    restart: always

  dbcrient:
    image: dpage/pgadmin4:8.8
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@example.com"
      PGADMIN_DEFAULT_PASSWORD: "example"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_SERVER_JSON_FILE: "/pgadmin4/servers.json"
      PGADMIN_PREFERENCES_JSON_FILE: "/pgadmin4/preferences.json"
    ports:
      - 5051:80
    volumes:
      - ./.pgadmin:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
      - ./config/preferences.json:/pgadmin4/preferences.json
    restart: always
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      target: dev
    volumes:
      - ./frontend:/frontend
    ports:
      - 3002:3000
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - api

  web:
    image: nginx:1.26.1-alpine
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - api
      - frontend
    # environment:
    #   - NGINX_HOST=foobar.com
    #   - NGINX_PORT=80

networks:
  default:
    name: docker-nestjs_default
# volumes:
# 開発環境ではボリュームはなし。
# 本番環境ではボリュームを利用する。
