services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      target: development
    volumes:
      - ./api:/api
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/practice?schema=public"
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    restart: always
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "practice"
    ports:
      - 5432:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d
    stdin_open: true
    tty: true
    restart: always
  dbcrient:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@example.com"
      PGADMIN_DEFAULT_PASSWORD: "example"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_SERVER_JSON_FILE: "/pgadmin4/servers.json"
      PGADMIN_PREFERENCES_JSON_FILE: "/pgadmin4/preferences.json"
    ports:
      - 5050:80
    volumes:
      - ./.pgadmin:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
      - ./config/preferences.json:/pgadmin4/preferences.json
    depends_on:
      - db
    restart: always
volumes:
  .api:
  db:
  .pgadmin:
