services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      target: development
    volumes:
      - ./api:/api
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    restart: always
    user: '1000'
volumes:
  db:
